/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package mx.maleficarum;

import org.mule.tools.cloudconnect.annotations.Connector;
import org.mule.tools.cloudconnect.annotations.Operation;
import org.mule.tools.cloudconnect.annotations.Property;

@Connector(namespacePrefix="rabbitmq")
public class RabbitMQCloudConnector {
	
	@Property
	private String queueName;
	
	@Property
	private String host;
	
	@Property
	private int port;
	
	@Property
	private String username;
	
	@Property
	private String password;
	
	
    public String getQueueName() {
		return queueName;
	}


	public void setQueueName(String queueName) {
		this.queueName = queueName;
	}


	public String getHost() {
		return host;
	}


	public void setHost(String host) {
		this.host = host;
	}


	public int getPort() {
		return port;
	}


	public void setPort(int port) {
		this.port = port;
	}


	public String getUsername() {
		return username;
	}


	public void setUsername(String username) {
		this.username = username;
	}


	public String getPassword() {
		return password;
	}


	public void setPassword(String password) {
		this.password = password;
	}


	/*
     * The following is a sample operation
     */
    @Operation
    public String send(String message) {
    	return message.toUpperCase();
    }
}